### ISSUE TITLE
Todo List?

### ISSUE THREAD

**Issue by jhollist** [ropensci/lawn#10]
@sckott I am essentially using the unconf as an excuse to close my door and ignore everything else on thurs and friday.  Whether or not I get involved remotely in other discussions doesn't matter much to me, it just provides me with a great cover for ignoring other stuff (thanks!).   I would be just as happy working on some functions for lawn (and working on the maptools task view).  

Are there any turf.js functions you'd like to see added or should I just try to pick off a few of them on Thursday and Friday?

**Comment by sckott** [comment]
hey jeff, cool! happy to help! nothing in particular in terms of turf functions, we can just keep plugging away until we got them all.  If we feel like it would be better to chat we can do so over skype, etc. I think you're already in our slack so we can chat there too

**Comment by sckott** [comment]
oh i guess we could make a little markdown list of turf.js functions left to do, and tick them off as we go?

**Comment by jhollist** [comment]
:+1:

**Comment by jhollist** [comment]
To Do List of turf.js functions:

# Aggregation
- [ ] [aggregate](http://turfjs.org/static/docs/module-turf_aggregate.html)
- [x] [average](http://turfjs.org/static/docs/module-turf_average.html)
- [x] [count](http://turfjs.org/static/docs/module-turf_count.html)
- [ ] [deviation](http://turfjs.org/static/docs/module-turf_deviation.html)
- [ ] [max](http://turfjs.org/static/docs/module-turf_max.html)
- [ ] [median](http://turfjs.org/static/docs/module-turf_median.html)
- [ ] [min](http://turfjs.org/static/docs/module-turf_min.html)
- [ ] [sum](http://turfjs.org/static/docs/module-turf_sum.html)
- [ ] [variance](http://turfjs.org/static/docs/module-turf_variance.html)

# Measurement
- [ ] [along](http://turfjs.org/static/docs/module-turf_along.html)
- [x] [area](http://turfjs.org/static/docs/module-turf_area.html)
- [ ] [bbox-polygon](http://turfjs.org/static/docs/module-turf_bbox-polygon.html)
- [ ] [bearing](http://turfjs.org/static/docs/module-turf_bearing.html)
- [ ] [center](http://turfjs.org/static/docs/module-turf_center.html)
- [ ] [centroid](http://turfjs.org/static/docs/module-turf_centroid.html)
- [ ] [destination](http://turfjs.org/static/docs/module-turf_destination.html)
- [x] [distance](http://turfjs.org/static/docs/module-turf_distance.html)
- [ ] [envelope](http://turfjs.org/static/docs/module-turf_envelope.html)
- [x] [extent](http://turfjs.org/static/docs/module-turf_extent.html)
- [ ] [line-distance](http://turfjs.org/static/docs/module-turf_line-distance.html)
- [ ] [midpoint](http://turfjs.org/static/docs/module-turf_midpoint.html)
- [ ] [point-on-surface](http://turfjs.org/static/docs/module-turf_point-on-surface.html)
- [ ] [size](http://turfjs.org/static/docs/module-turf_size.html)
- [ ] [square](http://turfjs.org/static/docs/module-turf_square.html)

# Transformation
- [ ] [bezier](http://turfjs.org/static/docs/module-turf_bezier.html)
- [x] [buffer](http://turfjs.org/static/docs/module-turf_buffer.html)
- [ ] [concave](http://turfjs.org/static/docs/module-turf_concave.html)
- [ ] [convex](http://turfjs.org/static/docs/module-turf_convex.html)
- [ ] [erase](http://turfjs.org/static/docs/module-turf_erase.html)
- [x] [intersect](http://turfjs.org/static/docs/module-turf_intersect.html)
- [ ] [merge](http://turfjs.org/static/docs/module-turf_merge.html)
- [ ] [simplify](http://turfjs.org/static/docs/module-turf_simplify.html)
- [x] [union](http://turfjs.org/static/docs/module-turf_union.html)

# Misc
- [ ] [combine](http://turfjs.org/static/docs/module-turf_combine.html)
- [ ] [explode](http://turfjs.org/static/docs/module-turf_explode.html)
- [ ] [flip](http://turfjs.org/static/docs/module-turf_flip.html)
- [ ] [kinks](http://turfjs.org/static/docs/module-turf_kinks.html)
- [ ] [line-slice](http://turfjs.org/static/docs/module-turf_line-slice.html)
- [ ] [point-on-line](http://turfjs.org/static/docs/module-turf_point-on-line.html)

# Helper
- [ ] [featurecollection](http://turfjs.org/static/docs/module-turf_featurecollection.html)
- [ ] [linestring](http://turfjs.org/static/docs/module-turf_linestring.html)
- [x] [point](http://turfjs.org/static/docs/module-turf_point.html)
- [ ] [polygon](http://turfjs.org/static/docs/module-turf_polygon.html)

# Data
- [x] [filter](http://turfjs.org/static/docs/module-turf_filter.html)
- [ ] [random](http://turfjs.org/static/docs/module-turf_random.html)
- [ ] [remove](http://turfjs.org/static/docs/module-turf_remove.html)
- [x] [sample](http://turfjs.org/static/docs/module-turf_sample.html)

# Interpolation
- [ ] [hex-grid](http://turfjs.org/static/docs/module-turf_hex-grid.html)
- [ ] [isolines](http://turfjs.org/static/docs/module-turf_isolines.html)
- [ ] [planepoint](http://turfjs.org/static/docs/module-turf_planepoint.html)
- [ ] [point-grid](http://turfjs.org/static/docs/module-turf_point-grid.html)
- [ ] [square-grid](http://turfjs.org/static/docs/module-turf_square-grid.html)
- [ ] [tin](http://turfjs.org/static/docs/module-turf_tin.html)
- [ ] [triangle-grid](http://turfjs.org/static/docs/module-turf_triangle-grid.html)

# Joins
- [ ] [inside](http://turfjs.org/static/docs/module-turf_inside.html)
- [ ] [tag](http://turfjs.org/static/docs/module-turf_tag.html)
- [x] [within](http://turfjs.org/static/docs/module-turf_within.html)

# Classification
- [ ] [jenks](http://turfjs.org/static/docs/module-turf_jenks.html)
- [ ] [nearest](http://turfjs.org/static/docs/module-turf_nearest.html)
- [ ] [quantile](http://turfjs.org/static/docs/module-turf_quantile.html)
- [ ] [reclass](http://turfjs.org/static/docs/module-turf_reclass.html)

**Comment by sckott** [comment]
awesome, thanks for making this @jhollist

**Comment by jhollist** [comment]
Sure thing!

The checklists are pretty slick!

On Thu, Mar 26, 2015 at 3:18 PM, Scott Chamberlain <notifications@github.com
> wrote:

> awesome, thanks for making this @jhollist <https://github.com/jhollist>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/lawn/issues/10#issuecomment-86677841>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by jhollist** [comment]
moving the checklist to a stand alone issue https://github.com/ropensci/lawn/issues/13
