### ISSUE TITLE
turf.js todo list

### ISSUE THREAD

**Issue by jhollist** [ropensci/lawn#13]
To Do List of turf.js functions:

# Aggregation
- [x] [aggregate](http://turfjs.org/static/docs/module-turf_aggregate.html)
- [x] [average](http://turfjs.org/static/docs/module-turf_average.html)
- [x] [count](http://turfjs.org/static/docs/module-turf_count.html)
- [x] [deviation](http://turfjs.org/static/docs/module-turf_deviation.html)
- [x] [max](http://turfjs.org/static/docs/module-turf_max.html)
- [x] [median](http://turfjs.org/static/docs/module-turf_median.html)
- [x] [min](http://turfjs.org/static/docs/module-turf_min.html)
- [x] [sum](http://turfjs.org/static/docs/module-turf_sum.html)
- [x] [variance](http://turfjs.org/static/docs/module-turf_variance.html)

# Measurement
- [x] [along](http://turfjs.org/static/docs/module-turf_along.html)
- [x] [area](http://turfjs.org/static/docs/module-turf_area.html)
- [x] [bbox-polygon](http://turfjs.org/static/docs/module-turf_bbox-polygon.html)
- [x] [bearing](http://turfjs.org/static/docs/module-turf_bearing.html)
- [x] [center](http://turfjs.org/static/docs/module-turf_center.html)
- [x] [centroid](http://turfjs.org/static/docs/module-turf_centroid.html)
- [x] [destination](http://turfjs.org/static/docs/module-turf_destination.html)
- [x] [distance](http://turfjs.org/static/docs/module-turf_distance.html)
- [x] [envelope](http://turfjs.org/static/docs/module-turf_envelope.html)
- [x] [extent](http://turfjs.org/static/docs/module-turf_extent.html)
- [x] [line-distance](http://turfjs.org/static/docs/module-turf_line-distance.html)
- [x] [midpoint](http://turfjs.org/static/docs/module-turf_midpoint.html)
- [x] [point-on-surface](http://turfjs.org/static/docs/module-turf_point-on-surface.html)
- [x] [size](http://turfjs.org/static/docs/module-turf_size.html)
- [x] [square](http://turfjs.org/static/docs/module-turf_square.html)

# Transformation
- [x] [bezier](http://turfjs.org/static/docs/module-turf_bezier.html)
- [x] [buffer](http://turfjs.org/static/docs/module-turf_buffer.html)
- [x] [concave](http://turfjs.org/static/docs/module-turf_concave.html)
- [x] [convex](http://turfjs.org/static/docs/module-turf_convex.html)
- [x] [erase](http://turfjs.org/static/docs/module-turf_erase.html)
- [x] [intersect](http://turfjs.org/static/docs/module-turf_intersect.html)
- [x] [merge](http://turfjs.org/static/docs/module-turf_merge.html)
- [x] [simplify](http://turfjs.org/static/docs/module-turf_simplify.html)
- [x] [union](http://turfjs.org/static/docs/module-turf_union.html)

# Misc
- [x] [combine](http://turfjs.org/static/docs/module-turf_combine.html)
- [x] [explode](http://turfjs.org/static/docs/module-turf_explode.html)
- [x] [flip](http://turfjs.org/static/docs/module-turf_flip.html)
- [x] [kinks](http://turfjs.org/static/docs/module-turf_kinks.html)
- [x] [line-slice](http://turfjs.org/static/docs/module-turf_line-slice.html)
- [x] [point-on-line](http://turfjs.org/static/docs/module-turf_point-on-line.html)

# Helper
- [x] [featurecollection](http://turfjs.org/static/docs/module-turf_featurecollection.html)
- [x] [linestring](http://turfjs.org/static/docs/module-turf_linestring.html)
- [x] [point](http://turfjs.org/static/docs/module-turf_point.html)
- [x] [polygon](http://turfjs.org/static/docs/module-turf_polygon.html)

# Data
- [x] [filter](http://turfjs.org/static/docs/module-turf_filter.html)
- [x] [random](http://turfjs.org/static/docs/module-turf_random.html)
- [x] [remove](http://turfjs.org/static/docs/module-turf_remove.html)
- [x] [sample](http://turfjs.org/static/docs/module-turf_sample.html)

# Interpolation
- [x] [hex-grid](http://turfjs.org/static/docs/module-turf_hex-grid.html)
- [x] [isolines](http://turfjs.org/static/docs/module-turf_isolines.html)
- [x] [planepoint](http://turfjs.org/static/docs/module-turf_planepoint.html)
- [x] [point-grid](http://turfjs.org/static/docs/module-turf_point-grid.html)
- [x] [square-grid](http://turfjs.org/static/docs/module-turf_square-grid.html)
- [x] [tin](http://turfjs.org/static/docs/module-turf_tin.html)
- [x] [triangle-grid](http://turfjs.org/static/docs/module-turf_triangle-grid.html)

# Joins
- [x] [inside](http://turfjs.org/static/docs/module-turf_inside.html)
- [x] [tag](http://turfjs.org/static/docs/module-turf_tag.html)
- [x] [within](http://turfjs.org/static/docs/module-turf_within.html)

# Classification
- [x] [jenks](http://turfjs.org/static/docs/module-turf_jenks.html)
- [x] [nearest](http://turfjs.org/static/docs/module-turf_nearest.html)
- [x] [quantile](http://turfjs.org/static/docs/module-turf_quantile.html)
- [x] [reclass](http://turfjs.org/static/docs/module-turf_reclass.html)

**Comment by sckott** [comment]
`FeatureCollection` is complicated. Trying to figure out best way to do this. On the user side, if they've already created some features and got back what we give back to them (lists), then passing those into a `featurecollection()` function requires that those lists be converted back into turf.js representations, so e.g.

```
point(c(-75.343, 39.984), properties = list(name = 'Location A'))
#> $type
#> [1] "Feature"
#> 
#> $geometry
#> $geometry$type
#> [1] "Point"
#> 
#> $geometry$coordinates
#> [1] -75.343  39.984
#> 
#> 
#> $properties
#> $properties$name
#> [1] "Location A"
#> 
#> attr(,"class")
#> [1] "point"
```
 
needs to get to 

```r
turf.point([-75.343, 39.984], {name: 'Location A'})
```

But this doesn't work easily using `toJSON()`. 

working on this

**Comment by sckott** [comment]
all done :fork_and_knife:

**Comment by jhollist** [comment]
wow, @sckott I just noticed you finished all these up!  Nice!

I may be able to carve out a few hours on this tomorrow.  Anything left to do for v0.1?  Tests?

**Comment by sckott** [comment]
Nothing I can think of left to do. The only thing now is dealing with fact that `leaflet` is not on CRAN yet. I've put it into Suggests so that it isn't required to install the package, but I believe CRAN changed to wanting all pkgs available from a CRAN like repo. Carl started a drat repo and I put that URL in the description file https://github.com/ropensci/lawn/blob/master/DESCRIPTION#L17 - and that seems to pass check, though I don't know a way of testing if that works for users - anyway, we could try submitting now, or be conservative and wait until leaflet is on CRAN. 

Anything else you think needs doing?

**Comment by sckott** [comment]
I'm beefing up a few tests
